### ISSUE TITLE
Using rustfmt.toml when formatting

### ISSUE THREAD

**Issue by LukasKalbertodt** [DamnWidget/anaconda_rust#10]
I want to use the format-on-save feature with some custom rustfmt options. Sadly it seems that AnacondaRust does not spawn `rustfmt` correctly. Rustfmt automatically checks in the current directory and parent directories for a `rustfmt.toml` file and uses it as configuration. But when using AnacondaRust it does not use my custom configuration. I think the easiest solution is to spawn `rustfmt` with the files directory as working directory. 

It might also be interesting for some to specify the `--config-path` of rustfmt in the AnacondaRust configuration.

I'd really appreciate if someone could look into this :)

**Comment by DamnWidget** [comment]
That is because the `rustfmt`command is ran from the JsonServer path and not from the current directory. I will take a look into this as soon as I have some free time (that is not much lately).

**Comment by LukasKalbertodt** [comment]
That would be awesome! Sadly I know very little about python and nothing about sublime plugin development. Otherwise I would have tried fixing it myself. I hope you'll find some time soon :)

**Comment by LukasKalbertodt** [comment]
I tried my best :)
