### ISSUE TITLE
0.2.2 will remove code unexpectedly

### ISSUE THREAD

**Issue by fengcen** [DamnWidget/anaconda_rust#13]
I'm just upgrade to 0.2.2 and when I format code, the code in the beginning(maybe two or three line) will be remove unexpectedly. You can check about that. 0.2.1 does not have this problem.

**Comment by DamnWidget** [comment]
You are right, working on it.

**Comment by DamnWidget** [comment]
Thank you for the valuable feedback, it is fixed now and v0.2.2 is re-packed and available on Package Control now
