### ISSUE TITLE
Auto format adds one empty line in the beginning of the file

### ISSUE THREAD

**Issue by LukasKalbertodt** [DamnWidget/anaconda_rust#16]
Whenever my first line of the file is empty and I auto-format it, the auto-format adds a new empty line in the beginning of my file. I could grow my file as long as I'd like to by triggering auto-format...

**Comment by DamnWidget** [comment]
Added commit, please, close if it fix your issue

**Comment by LukasKalbertodt** [comment]
@DamnWidget it doesn't work: the line `Using rustfmt config file /foo/bla/rustfmt.toml` is always added... :crying_cat_face: Seems like a bug in `rustfmt`... or their definition of `Plain` differs from mine :/

**Comment by DamnWidget** [comment]
I am not sure why anyone would add useless logs to a command line application that spits it's output using the standard output, I mean, come on.

I will take a look as soon as I have a break, are the other two issues fixed?

**Comment by DamnWidget** [comment]
This one should be fixed now as well

**Comment by LukasKalbertodt** [comment]
As you can see in the [packagecontrol.io graph](https://packagecontrol.io/packages/anaconda_rust), quite a few people have installed this plugin today :wink: 

So far it seems fine! Thanks for investing your time, I really appreciate it :)

I hadn't had the time trying it out myself but my students said it works well. No major issues. Apparently an empty file causes a crash or something, but that is the only issue I noticed.

(I will just close all three issues -- if something is wrong still, I can still reopen them)

**Comment by DamnWidget** [comment]
No problem Lukas.

**Comment by DamnWidget** [comment]
Hey @LukasKalbertodt, take a look at [this](https://github.com/DamnWidget/rust-anaconda) it is coming for the 1.0.0 release.
