### ISSUE TITLE
`check_racer_version` failed because of error environment variables.

### ISSUE THREAD

**Issue by loggerhead** [DamnWidget/anaconda_rust#18]
The console of sublime keeps outputing following logging:

```
Can't determine racer version: Command '['racer', '-V']' returned non-zero exit status 1
```

I have installed `racer`, `rustfmt` and `rustc` correctly, and checked it works by execute the command `racer -V` in command line. To locate the problem, I have checked the code and found `check_racer_version` can't get the correct environment variables which set in `~/.zshrc`. So `data = subprocess.check_output([racer, '-V'], env=env)` will failed.

The version of related software is below:
- AnacondaRust v0.2.7
- Sublime Text build 3114
- OS X 10.10.5
- zsh 5.2

**Comment by DamnWidget** [comment]
What do you mean with "get correct environment variables"? The environment variables are passed by ST3 process to Anaconda or not, is common for ST3 to don't inherit any SHELL profile defined variables if you start it using the GUI.

If you just start it from a command line interpreter it will inherit the variables just fine, anyway, all the process to configure the plugin to don't depend on SHELL variables is described in [this section](https://github.com/DamnWidget/anaconda_rust#configure-anacondarust) of the README.md

**Comment by loggerhead** [comment]
> If you just start it from a command line interpreter it will inherit the variables just fine, anyway, all the process to configure the plugin to don't depend on SHELL variables is described in this section of the README.md

Even after config as belowing, I still get the same error message.

``` json
{
    "rustc_binary_path": "/Users/loggerhead/.cargo/bin/rustc",
    "racer_binary_path": "/Users/loggerhead/.cargo/bin/racer",
    "rustfmt_binary_path": "/Users/loggerhead/.cargo/bin/rustfmt",
    "rust_src_path": "/Users/loggerhead/.cargo/rust-1.10.0-src/src",
}
```

**Comment by DamnWidget** [comment]
Can you provide with any log from the ST3 terminal and from your `~/Library/Cache/Jedi/<your_project_name>/anconda_jsonserver.log`, if you don't have a project name, probably there is a directory called `anaconda` that contains the file.

**Comment by divinites** [comment]
I have the same problem and I cannot find relevant log in the folder you pointed out...

**Comment by DamnWidget** [comment]
If you are using anaconda v2 the logs are now in `~/Library/Logs/Anaconda`

**Comment by divinites** [comment]
I solved this problem,since I found that the src path setting is wrong... I guess that @loggerhead might have the same problem, in my case, it is rustc-1.10.0, not rust-1.10.0

**Comment by loggerhead** [comment]
The problem is gone after I update the plugin and rust components.
