### ISSUE TITLE
anaconda_rust didn't work.

### ISSUE THREAD

**Issue by zoumi** [DamnWidget/anaconda_rust#19]
### My system info:

Windows 7 ultimate 64bit
Sublime Text Build 3059
Rust nightly GNU 1.10 32bit
#### My anaconda_rust settings:

:
{
    "rustc_binary_path": "E:\rustdir\bin\rustc",
    "racer_binary_path": "E:\rustdir\bin\racer",
    "rustfmt_binary_path": "E:\rustdir\bin\rustfmt",
    "rust_src_path": "H:\Rust\src",
}
### This is the info from sublime console:

DPI scale: 1
startup, version: 3059 windows x32 channel: stable
executable: /E/Program Files (x86)/Sublime Text Build 3059/sublime_text.exe
working dir: /E/Program Files (x86)/Sublime Text Build 3059
packages path: /E/Program Files (x86)/Sublime Text Build 3059/Data/Packages
state path: /E/Program Files (x86)/Sublime Text Build 3059/Data/Local
hardware concurrency: 8
zip path: /E/Program Files (x86)/Sublime Text Build 3059/Packages
zip path: /E/Program Files (x86)/Sublime Text Build 3059/Data/Installed Packages
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 6 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 163 cache hits: 163
pre session restore time: 0.267479
startup time: 0.375479
first paint time: 0.386479
launching: /E/Program Files (x86)/Sublime Text Build 3059/plugin_host.exe
loaded 839 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin 0_package_control_loader.10-golangconfig
reloading plugin 0_package_control_loader.10-shellenv
reloading plugin 0_package_control_loader.20-newterm
reloading plugin 0_package_control_loader.20-package_events
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Anaconda.anaconda
reloading plugin Anaconda.setup
reloading plugin Anaconda.version
reloading plugin anaconda_rust.anaconda_rust
reloading plugin anaconda_rust.plugin_version
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2016-08-01 20:39:20, next run at 2016-08-01 21:39:20 or after

![o1](https://cloud.githubusercontent.com/assets/5162901/17294904/16aa5f00-582c-11e6-826f-06bec2b04961.png)
![image](https://cloud.githubusercontent.com/assets/5162901/17295146/5b7a6d72-582d-11e6-871d-8b085605b45c.png)

**Comment by DamnWidget** [comment]
Any special reason about why do you use an outdated ST3 version?

**Comment by zoumi** [comment]
@DamnWidget 
I have installed the "Rust" plugin for Sublime text. And now everything works.

**Comment by zoumi** [comment]
@DamnWidget 
Ok, I have updated Sublime Text 3 to the newest version.It works now.Thank you so much.

**Comment by DamnWidget** [comment]
No problem :)
