### ISSUE TITLE
anaconda_rust does not auto-complete

### ISSUE THREAD

**Issue by divinites** [DamnWidget/anaconda_rust#2]
I installed anaconda_rust and configure everything in the setting file, the autofmt works, but racer no. There is no error output on console either. I have no clue about where the problem is. I post my configure file below for your information.

`
{

```
"anaconda_rust_linting": true,
"anaconda_rust_autocompletion": true,

"rustc_binary_path": "/usr/local/bin/rustc",
"racer_binary_path": "/Users/divinites/.cargo/bin/racer",
"rustfmt_binary_path": "/Users/divinites/.cargo/bin/rustfmt",
"rust_src_path": "/Users/divinites/dropbox/usr/src/rustc-1.7.0/src",
"rust_format_on_save": true,
"rust_rustfmt_timeout": 1  // seconds
```

}
`

**Comment by DamnWidget** [comment]
HI @divinites 
Can you take a look at `~/Library/Caches/Jedi/<your_project_name>/anaconda_jsonserver.log` and post it's content in pastebin or similar?

**Comment by divinites** [comment]
Here you are.

http://pastebin.com/Q5mRSGXX

**Comment by divinites** [comment]
So instead of using racerd, you are using jedi server + racer to serve the auto-complete?

**Comment by DamnWidget** [comment]
No, it doesn't use Jedi at all, I will take a look as soon as I can

**Comment by DamnWidget** [comment]
Which version of racer are you using? Seems like you have installed an old version that does not supports the `tab-text` option as interface mode. You can check your racer version just writing `racer -V`, I recommend you to update to racer 1.2.9 that is the current last version.

**Comment by divinites** [comment]
upgrading to 1.2.9 solved my problem, I can now uninstall rust_autocomplete and rust_format plugins, thanks for your work!

**Comment by DamnWidget** [comment]
I am glad to see that your problems are now resolved, by the way, that is why I created anaconda_rust because I don't like to have two or three packages to do something that can be done in a single package, that is exactly the reason that I created anaconda in first place :)
