### ISSUE TITLE
Error parsing the new build message format.

### ISSUE THREAD

**Issue by diaphore** [DamnWidget/anaconda_rust#21]
The plugin fails to parse the recently introduced build messages :

```
error[E0433]: failed to resolve. Use of undeclared type or module `Foo`
   --> main.rs:129:15
    |
129 |     let foo = Foo::new(123);
    |               ^^^^^^^^ Use of undeclared type or module `Foo`
```

c.f. https://github.com/rust-lang/sublime-rust/pull/85 for a possible fix.

**Comment by DamnWidget** [comment]
I understand that the latest versions of `rustc` produce text like the first line in your pasted log right?

**Comment by diaphore** [comment]
@DamnWidget My version outputs build messages as reported, the whole 5 lines.

```
$ rustc --version
rustc 1.13.0-nightly (70598e04f 2016-09-03)
```

Not sure when it was introduced, I've been out of the rust loop lately.

**Comment by DamnWidget** [comment]
Seems like the last version (1.13.0-nightly) introduced the new format, we **must** provide support for nightly, beta and stable versions so unfortunately the example PR that you kindly pointed us to is not of any use for us.

Anyway, I already have a fix so it will be released soon. Thanks for pointing to this issue.

**Comment by diaphore** [comment]
@DamnWidget Even better, thanks.
