### ISSUE TITLE
Any shortcut to close minihtml message?

### ISSUE THREAD

**Issue by divinites** [DamnWidget/anaconda_rust#22]
I know this probably is not a problem of Anaconda, but since anaconda uses this new property, so I think it would be okay to ask here.

Frequently I encountered compiling error message shown in minihtml like this:

<img width="504" alt="09_13_16 at 11 24 09am" src="https://cloud.githubusercontent.com/assets/7761537/18470506/bb7b9640-79a4-11e6-854c-9906e675cb36.png">

How can I easily close this message without touching the mouse?

**Comment by DamnWidget** [comment]
I never made anaconda do that explicitly you get that from file linting?

**Comment by DamnWidget** [comment]
Oh, you get those from the build system, I have no idea how those works, those are the new "phantoms" for doc panels. Look for any Sublime Text 3 configuration option/key binding including the "phantom" word.

You can probably do something like add a shortcut:

``` javascript
{ "keys": ["ctrl+k", "ctrl+p"], "command": "erase_phantoms" , "args": {"key": "exec"}}
```

P.S: I didn't test it but the command `view.erase_phantoms('exec')` works in the ST3 console

**Comment by divinites** [comment]
Unfortunately no, it does not work. There is a discussion thread on the Sublime text forum, and the conclusion is that, currently there is no way to set a shortcut to erease the phantom.

https://forum.sublimetext.com/t/keyboard-binding-to-dismiss-inline-build-errors/21956

This is not a problem of Anaconda, but that of Sublime Text itself, I suggest that you can close this issue at this moment.

**Comment by DamnWidget** [comment]
There is one guy saying that you can disable the behaviour setting `show_errors_inline` as `false` anyway, you could make a shortcut works but you need to create a plugin in your `Packages` directory, the content of the plugin would be very simple something like:

``` python
import sublime
import sublime_plugin 


class GetTheFuckOffHere(sublime_plugin.WindowCommand):
    """Get the fuck off here man
    """"

    def run(self):
       self.window.active_view().erase_phantoms('exec')
```

Then you just create a shortcut

``` javascript
{ "keys": ["ctrl+k", "ctrl+p"], "command": "get_the_fuck_off_here"}
```

Put the python file into a directory with whatever name you want and name the file whatever you want as well, this will do the trick.

**Comment by divinites** [comment]
brilliant! It works.

**Comment by DamnWidget** [comment]
Of course it does :P
