### ISSUE TITLE
Linter fails with multiple targets.

### ISSUE THREAD

**Issue by ehuss** [DamnWidget/anaconda_rust#23]
If I have a basic project with a main.rs and lib.rs, the linter fails with this message:

```error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target```

I'm fairly new to Rust, so I'm not entirely certain if there is some workaround, or if I have misconfigured anything.

**Comment by DamnWidget** [comment]
Hi, where do you get that message, in the ST3 console?
Which operating system are you on?

**Comment by ehuss** [comment]
I'm sorry, this was actually an error with the Rust Enhanced package.
