### ISSUE TITLE
Autoformat crashed when the file contains unicode characters

### ISSUE THREAD

**Issue by ethe** [DamnWidget/anaconda_rust#26]
```
  File "/Users/guozixing/Library/Application Support/Sublime Text 3/Packages/anaconda_rust/commands/rustfmt.py", line 57, in run
    tmp.write(self.code)
UnicodeEncodeError: 'ascii' codec can't encode character '\uff1a' in position 191: ordinal not in range(128)
```

I am sure that it is a bug.

**Comment by DamnWidget** [comment]
Hi @ethe 
Can you run the code below in your ST3 console and let me know which encoding is being printed?
```python
import sys;print(sys.stdin.encoding);
```

By the way, which version of Python is running the anaconda's JsonServer? You can check it with `ps aux | grep jsonserver`

**Comment by ethe** [comment]
```
>>> import sys; print(sys.stdin.encoding)
US-ASCII
```


JsonServer runs at CPython 2.7.12.

**Comment by DamnWidget** [comment]
That is the problem, your ST3 is encoding the text in ASCII and you are probably using some Chinese characters you need to tell ST3 to use UTF8.

If you run `locale` command in your OSX terminal what do you get? You should be using something like `zh_CN.UTF-8` if your system is in Chinese language or `en_US.UTF-8` if it is in English. You should probably also check if you have an environment variable called `PYTHONENCODING` (you can check it running `export | grep PYTHONENCODING`) if it exists make sure it's encoding is UTF8.

If your terminal reports any type of `UTF8` encoding try to close your ST3 with `Cmd+Q` and open it from the terminal running `subl` it will probably inherit the encoding from the terminal environment and work just fine.

**Comment by ethe** [comment]
I think my commit fixed it by a easier way.

**Comment by ethe** [comment]
Thanks for your suggestions, I set the environment variable and there is no problem if I running Sublime as `subl`, but I still think the above change I committed is easier to use, so I kept it.

**Comment by DamnWidget** [comment]
I will consider to merge that PR if more users are affected by this in the future but being an environmental problem and not an anaconda_rust problem I doubt it get included. You will also take a look at your `language and region` settings in your Mac they are probably miss configured.

**Comment by ethe** [comment]
Encoding `self.code` into UTF-8 has no obvious drawback.
