### ISSUE TITLE
rustfmt fails when `rustfmt.toml` not available

### ISSUE THREAD

**Issue by shiman** [DamnWidget/anaconda_rust#33]
When I saved my `.rs` file, my whole contents were replaced by the error message from `rustfmt`:

```
Error: unable to find a config file for the given path: `C:\Users\guosh\AppData\Roaming\Sublime`

usage: C:\Users\guosh\.cargo\bin\rustfmt [options] <file>...

Options:
    -h, --help          show this message
    -V, --version       show version information
    -v, --verbose       print verbose output
        --write-mode [replace|overwrite|display|diff|coverage|checkstyle]
                        mode to write in (not usable when piping from stdin)
        --skip-children
                        don't reformat child modules
        --config-help   show details of rustfmt configuration options
        --dump-default-config PATH
                        Dumps the default configuration to a file and exits.
        --dump-minimal-config PATH
                        Dumps configuration options that were checked during
                        formatting to a file.
        --config-path [Path for the configuration file]
                        Recursively searches the given path for the
                        rustfmt.toml config file. If not found reverts to the
                        input file path
        --file-lines JSON
                        Format specified line ranges. See README for more
                        detail on the JSON format.
```
And what is worse, the file was somehow saved automatically, and I lost all my contents..

rustfmt version: 0.9.0-nightly ( )
Environment: Windows 10, sublime text 3
AnacondaRust version: 0.2.10

After some research, I found that this is because anaconda_rust calls `rustfmt` with the option `--config-path` (`rust_rustfmt_config_path` in the package config json file), which, if not specified, will default to current working directory. The code is [here](https://github.com/DamnWidget/anaconda_rust/blob/0845be4420a6c4eb65bc3e8882d9e64a994818ad/commands/rustfmt.py#L59) and [here](https://github.com/DamnWidget/anaconda_rust/blob/cc652a957e1bd1624605ae265b1314b2c8e9c4ea/plugin/handlers_rust/commands/rustfmt.py#L59). On `rustfmt`'s side, when the `rustfmt.toml` can't be found at the specified config path, it will just output an error message ([to stdout!](https://github.com/rust-lang-nursery/rustfmt/blob/master/src/bin/rustfmt.rs#L313)) and quit.

This issue might be specific to the rustfmt version or the operating system. However, I would like to propose some possible workarounds:

- Put a note in the README file to show that it is mandatory to set `rust_rustfmt_config_path` where `rustfmt.toml` must exist.
- OR, when `rust_rustfmt_config_path` is not set, check the current working directory whether `rustfmt.toml` or `.rustfmt.toml` can be found. If yes, then use the current working directory as the `--config-path`'s value; otherwise, call `rustfmt` without `--config-path`.

If the second one is preferred, I can also help with the implementation.

**Comment by DamnWidget** [comment]
I don't believe that behavior has been always the default behavior for `rustfmt` regarding the config file path. I think your suggestions make sense, feel free to implement it and make a PR.

Thanks, by the way.

**Comment by shiman** [comment]
Please review when you got a chance.  #35  The patch fixed two things:
- `--config-path` will not be used when the user's config does not have a non-empty `rust_rustfmt_config_path` value
- Captures the error message by checking `rustfmt`'s return code and `stdout` and raises exception. [`rustfmt`'s error messages always go to `stdout`](https://github.com/rust-lang-nursery/rustfmt/issues/1979). With this fix, the user will see "The auto formatting failed!" in the status bar if there is something wrong with the config file. Previously, if the config is not available or is in bad format, the auto-formatting's progress bar would swing forever and prevent you from editing your code.

**Comment by DamnWidget** [comment]
Thank you @shiman I'll take a look later after work :+1:
