### ISSUE TITLE
Feature Request: RLS

### ISSUE THREAD

**Issue by LovingMelody** [DamnWidget/anaconda_rust#37]
Please add support for the [rust language server](https://github.com/rust-lang-nursery/rls)

**Comment by DamnWidget** [comment]
Looks like there is a lot of movement lately into implementation of the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol) and probably would be wise to make a  movement in the future but, which advantages over our current implementation has it currently? 

Implement it will require lot of effort and I have no time to do it and sadly I am the only maintainer of this plugin.

**Comment by LovingMelody** [comment]
> It supports functionality such as 'goto definition', symbol search, reformatting, and code completion, and enables renaming and refactorings.

It isn't a replacement for Racer, just put it  in as a low priority thing. I have been enjoying the real time error messages as I type though.
