### ISSUE TITLE
Provide an option to disable auto format

### ISSUE THREAD

**Issue by mbarakaja** [DamnWidget/anaconda_rust#8]
Actually **rustfmt** runs automatically each time a document is saved. I can't find a way to disable it. If I remove the **`rustfmt_binary_path`** from the configuration files, sublime text freezes.

**Comment by DamnWidget** [comment]
Just set `rust_format_on_save` as `false` in the config file

**Comment by mbarakaja** [comment]
I'm sorry, I just figure out now how to get the list of default configuration values for AnacondaRust in Sublime Text and there is indeed the option **`rust_format_on_save`**
